# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CAMERA.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CAMERA.proto',
  package='camera_msgs',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0c\x43\x41MERA.proto\x12\x0b\x63\x61mera_msgs\"3\n\x0b\x43\x61meraFrame\x12\x11\n\tcamera_id\x18\x01 \x01(\t\x12\x11\n\tjpeg_data\x18\x02 \x01(\x0c\"J\n\x0b\x43\x61meraBatch\x12(\n\x06\x66rames\x18\x01 \x03(\x0b\x32\x18.camera_msgs.CameraFrame\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x62\x06proto3')
)




_CAMERAFRAME = _descriptor.Descriptor(
  name='CameraFrame',
  full_name='camera_msgs.CameraFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='camera_id', full_name='camera_msgs.CameraFrame.camera_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='jpeg_data', full_name='camera_msgs.CameraFrame.jpeg_data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=80,
)


_CAMERABATCH = _descriptor.Descriptor(
  name='CameraBatch',
  full_name='camera_msgs.CameraBatch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frames', full_name='camera_msgs.CameraBatch.frames', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='camera_msgs.CameraBatch.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=156,
)

_CAMERABATCH.fields_by_name['frames'].message_type = _CAMERAFRAME
DESCRIPTOR.message_types_by_name['CameraFrame'] = _CAMERAFRAME
DESCRIPTOR.message_types_by_name['CameraBatch'] = _CAMERABATCH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CameraFrame = _reflection.GeneratedProtocolMessageType('CameraFrame', (_message.Message,), dict(
  DESCRIPTOR = _CAMERAFRAME,
  __module__ = 'CAMERA_pb2'
  # @@protoc_insertion_point(class_scope:camera_msgs.CameraFrame)
  ))
_sym_db.RegisterMessage(CameraFrame)

CameraBatch = _reflection.GeneratedProtocolMessageType('CameraBatch', (_message.Message,), dict(
  DESCRIPTOR = _CAMERABATCH,
  __module__ = 'CAMERA_pb2'
  # @@protoc_insertion_point(class_scope:camera_msgs.CameraBatch)
  ))
_sym_db.RegisterMessage(CameraBatch)


# @@protoc_insertion_point(module_scope)
