# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HMI_RX_CONTROLS.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15HMI_RX_CONTROLS.proto\"$\n\x08Waypoint\x12\x0b\n\x03lat\x18\x01 \x01(\x02\x12\x0b\n\x03lon\x18\x02 \x01(\x02\"\x80\x01\n\nNavigation\x12\x13\n\x0b\x63urrent_lat\x18\x01 \x01(\x02\x12\x13\n\x0b\x63urrent_lon\x18\x02 \x01(\x02\x12\x13\n\x0bheading_deg\x18\x03 \x01(\x02\x12\x1c\n\twaypoints\x18\x04 \x03(\x0b\x32\t.Waypoint\x12\x15\n\rsafety_states\x18\x05 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HMI_RX_CONTROLS_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WAYPOINT._serialized_start=25
  _WAYPOINT._serialized_end=61
  _NAVIGATION._serialized_start=64
  _NAVIGATION._serialized_end=192
# @@protoc_insertion_point(module_scope)
