# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HMI_TX_CONTROLS.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='HMI_TX_CONTROLS.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15HMI_TX_CONTROLS.proto\"\x1f\n\rEngageRequest\x12\x0e\n\x06\x65ngage\x18\x01 \x01(\x05\x62\x06proto3'
)




_ENGAGEREQUEST = _descriptor.Descriptor(
  name='EngageRequest',
  full_name='EngageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='engage', full_name='EngageRequest.engage', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=56,
)

DESCRIPTOR.message_types_by_name['EngageRequest'] = _ENGAGEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EngageRequest = _reflection.GeneratedProtocolMessageType('EngageRequest', (_message.Message,), {
  'DESCRIPTOR' : _ENGAGEREQUEST,
  '__module__' : 'HMI_TX_CONTROLS_pb2'
  # @@protoc_insertion_point(class_scope:EngageRequest)
  })
_sym_db.RegisterMessage(EngageRequest)


# @@protoc_insertion_point(module_scope)
