# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: percept_message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15percept_message.proto\x12\nperception\"*\n\x0bSignalValue\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\xb4\x01\n\x0ePerceptMessage\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\x12\x14\n\x0cmessage_name\x18\x02 \x01(\t\x12\x0e\n\x06\x63\x61n_id\x18\x03 \x01(\r\x12\x0b\n\x03\x64lc\x18\x04 \x01(\r\x12\x10\n\x08raw_data\x18\x05 \x01(\x0c\x12\x30\n\x0f\x64\x65\x63oded_signals\x18\x06 \x03(\x0b\x32\x17.perception.SignalValue\x12\x19\n\x11timestamp_iso8601\x18\x07 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'percept_message_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SIGNALVALUE._serialized_start=37
  _SIGNALVALUE._serialized_end=79
  _PERCEPTMESSAGE._serialized_start=82
  _PERCEPTMESSAGE._serialized_end=262
# @@protoc_insertion_point(module_scope)
